---
- hosts: web
  become: yes
  tasks:
  - name: Create test_user
    ansible.builtin.user:
      name: "test_user"
      shell: "/bin/bash"

  - name: Create /home/test_user/test_dir directory
    # TODO: fileモジュールでディレクトリを作成する
    #         パス: /home/test_user/test_dir
    #         パーミッション: 0755

  - name: Add line `export HOST_ENV_NAME=dev` in bashrc for test_user
    # TODO: lineinfileモジュールでファイルを変更する
    #         /home/test_user/.bashrc に `export HOST_ENV_NAME=dev` を追加する
    #         すでにHOST_ENV_NAMEがexportされている場合は `export export HOST_ENV_NAME=dev` になるようにする
