version: '3'
services:
  control_node:
    build:
      context: ..
      dockerfile: Dockerfile.control_node
    image: ansible_workshop_control_node
    container_name: ansible_control_node
    volumes:
      - .:/work
    tty: true
  managed_node:
    build:
      context: ..
      dockerfile: Dockerfile.managed_node
    image: ansible_workshop_managed_node
    container_name: ansible_managed_node
    ports:
      - 22
    tty: true
    privileged: true
  managed_node2:
    build:
      context: ..
      dockerfile: Dockerfile.managed_node
    image: ansible_workshop_managed_node
    container_name: ansible_managed_node2
    ports:
      - 22
    tty: true
    privileged: true
